// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQjhNAeRVp9sOfgr8VlzQ12T3Arvs2Zko',
    appId: '1:703537237635:web:87a49bba6bcb9b334915b6',
    messagingSenderId: '703537237635',
    projectId: 'proyecto-flutter-lyb',
    authDomain: 'proyecto-flutter-lyb.firebaseapp.com',
    storageBucket: 'proyecto-flutter-lyb.firebasestorage.app',
    measurementId: 'G-2K6XTKZKLV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFm2uPohXFLCJ06AWxcmrLCIVrWe5bP2I',
    appId: '1:703537237635:android:c846bfd227fe7a554915b6',
    messagingSenderId: '703537237635',
    projectId: 'proyecto-flutter-lyb',
    storageBucket: 'proyecto-flutter-lyb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSCoPPdBC9WH7-DX4IZ97qVN9BsrLGcLo',
    appId: '1:703537237635:ios:a76195a9817f6ec14915b6',
    messagingSenderId: '703537237635',
    projectId: 'proyecto-flutter-lyb',
    storageBucket: 'proyecto-flutter-lyb.firebasestorage.app',
    iosBundleId: 'com.example.prueba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSCoPPdBC9WH7-DX4IZ97qVN9BsrLGcLo',
    appId: '1:703537237635:ios:a76195a9817f6ec14915b6',
    messagingSenderId: '703537237635',
    projectId: 'proyecto-flutter-lyb',
    storageBucket: 'proyecto-flutter-lyb.firebasestorage.app',
    iosBundleId: 'com.example.prueba',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQjhNAeRVp9sOfgr8VlzQ12T3Arvs2Zko',
    appId: '1:703537237635:web:3d889ad63df7f00f4915b6',
    messagingSenderId: '703537237635',
    projectId: 'proyecto-flutter-lyb',
    authDomain: 'proyecto-flutter-lyb.firebaseapp.com',
    storageBucket: 'proyecto-flutter-lyb.firebasestorage.app',
    measurementId: 'G-RBPR6R5DBK',
  );

}